version: "3.8"
services:
  backend:
    container_name: app-backend
    build: ./docker/go
    depends_on:
      - db
    image: backend
    tty: true
    volumes:
      - ./:/menu_and_shopping_list
    ports:
      - 8080:8080
  db:
    image: mysql:8.1.0
    platform: "linux/amd64"
    container_name: app-database
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: menu_and_shopping_list
      TZ: Asia/Tokyo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
  forntend:
    container_name: app-frontend
    build: ./docker/react
    image: frontend
    tty: true
    volumes:
      - ./:/menu_and_shopping_list
    ports:
      - 5173:5173

volumes:
  mysql-data:
